In [18]:
import pandas as pd
import numpy as np

In [19]:
# Load the datasets
posts_df = pd.read_csv('Dataset/reddit_posts.csv')
comments_df = pd.read_csv('Dataset/reddit_post_comments.csv')

posts_df.head()

,post_id,subreddit,created_utc,selftext,post_url,post_title,link_flair_text,score,num_comments,upvote_ratio,post_author
0,kf0d1g,WomensHealth,1.608222e+09,"Hey! I spoke with them on the phone, and they ...",https://www.reddit.com/r/WomensHealth/comments...,Please sign petition to get nerves in the clit...,NaN,2466,183,1.00,jessica_pin
1,dwup3z,Healthyhooha,1.573842e+09,NaN,https://i.redd.it/ua4z8e477wy31.jpg,I know this is apart of the standardized proce...,NaN,2407,49,0.99,NaN
2,hamqgj,Periods,1.592380e+09,NaN,https://i.redd.it/h83zzjacdf551.jpg,I'm sure every person here relates.,Fluff,2357,16,1.00,noorhaider97
3,j8mxtl,Periods,1.602346e+09,NaN,https://i.redd.it/2fo1u3ioias51.jpg,🩸,Fluff,2176,16,1.00,NaN
4,mqc0v5,Periods,1.618349e+09,NaN,https://i.redd.it/83x11rfxd0t61.jpg,why is this so true?,Fluff,2113,72,1.00,KitKat1287

In [20]:
comments_df.head()

  post_id                                            comment         author
0  kf0d1g  Oh no. Oh no NO. I’m so sorry. Signed sealed d...  ohhh_RaMoannn
1  kf0d1g     Why are vaginas still taboo??? I don’t get it.       Dracalia
2  kf0d1g  *Has this been cross posted to r/twoxchromosom...         bex505
3  kf0d1g  How does their excuse that it "doesn't fit the...    shanaenae91
4  kf0d1g   Signed and donated 5000 shares. You are a saint!    BooBooCanoe

In [21]:
# Handle missing values
posts_df.fillna('', inplace=True)
comments_df.fillna('', inplace=True)

In [22]:
posts_df.head()

,post_id,subreddit,created_utc,selftext,post_url,post_title,link_flair_text,score,num_comments,upvote_ratio,post_author
0,kf0d1g,WomensHealth,1.608222e+09,"Hey! I spoke with them on the phone, and they ...",https://www.reddit.com/r/WomensHealth/comments...,Please sign petition to get nerves in the clit...,,2466,183,1.00,jessica_pin
1,dwup3z,Healthyhooha,1.573842e+09,,https://i.redd.it/ua4z8e477wy31.jpg,I know this is apart of the standardized proce...,,2407,49,0.99,
2,hamqgj,Periods,1.592380e+09,,https://i.redd.it/h83zzjacdf551.jpg,I'm sure every person here relates.,Fluff,2357,16,1.00,noorhaider97
3,j8mxtl,Periods,1.602346e+09,,https://i.redd.it/2fo1u3ioias51.jpg,🩸,Fluff,2176,16,1.00,
4,mqc0v5,Periods,1.618349e+09,,https://i.redd.it/83x11rfxd0t61.jpg,why is this so true?,Fluff,2113,72,1.00,KitKat1287

In [23]:
posts_df.shape

(2000, 11)

In [24]:
posts_df.drop_duplicates(subset='post_id', inplace=True)
posts_df.shape

(2000, 11)

In [25]:
comments_df.shape

(87679, 3)

In [26]:
comments_df.drop_duplicates(inplace=True)
comments_df.shape

(85825, 3)

In [27]:
# Extract unique users from posts and comments
post_authors = posts_df['post_author'].unique()
comment_authors = comments_df['author'].unique()
unique_users = set(post_authors) | set(comment_authors)

In [29]:
print(unique_users)
print(f'Number of unique Users: {len(unique_users)}')

{'', 'resonatebliss', 'Imchildfree', 'Ill_Ocelot_9155', 'cynical_genius', 'No-Adhesiveness403', 'Particular_Wall6390', 'Embarrassed_Dust7985', 'Halfling_bard-mom', 'FlimsyBirdy', 'tinycanteen', 'momofdagan', 'nps2790', 'Alternative_Bet7328', 'KeeleyHazier', 'littlebipper4', 'flippermode', 'kboom100', 'Dandelion33', 'carenrose', 'the-asian_kid', 'Santi159', 'AmbitiousYetMoody', 'b_elle', 'irenesias', 'Special_Hour_8915', 'mirrrje', 'orbitscum', 'Jaded_Cauliflower_50', 'cmmndr_wdw', 'yvettewithluv', 'blckpixels', 'xaea22', 'Skittles_the_Jester', 'bbbojackhorseman', 'Radiant-Tune-4411', 'Harmonyroller', 'onegoodbumblebee', 'MuchMadnessIs', 'broccoliqueen_72', 'omnixe-13c', 'MammaKrissJenner', '44_Sunflower_44', 'Depression_freak3347', 'emmivan', 'schoolpsych2005', 'OhListy', 'sadboilure', 'throwawawawawaysb', 'mynameisysabel', 'Marhelton', 'Campanella82', 'BigBeautifulTonks', 'TroublesomeFox', 'Mega_Minder6969', 'throwaway_hollerway', 'verybadhunting', 'TheLovelyLivvie', 'mei2207', 'daldalda', 'CyCheye', 'Witty_Cherry4607', 'Rastagoldilox', 'smallgodofsocks', 'IDidItWrongLastTime', 'deadsyren94', 'undifferentiatedbark', 'miris50', 'Pancake_Bunny', 'TheeNatorious', 'krobegdop', 'Same-Skill3118', 'safadancer', 'haydenmutt', 'AmbassadorCool2603', 'justadumbthrowaw4y', 'raimbowfright', 'ObjectiveNewspaper85', 'Hunnilisa', 'teenietemple', 'honey_1989', 'Lumpy-Recipe', 'UhhKing811', 'hillhillhillree', 'EllyEinhorn', 'snuggleallthekitties', 'No-Property9090', 'alynn101', 'Jerbear265', 'Yuulfuji', 'mdyml', 'guysaresocute', 'mlauraa93', 'Llewny', 'foxie11td', 'RAenigma3', 'vocalfreesia', 'Valleygirl81', 'MajesticL', 'ExcitingTangerine373', 'Sad_Bookkeeper5757', 'ictoan', 'User564368', 'Actual_Ad6304', 'hotestablishment007', 'cl0akincellar', 'Temporary_Celery9033', 'lulumelody', 'Late-Adhesiveness652', 'ThiefOfADHD', 'haleyrosaa4', 'Haley178', 'Gloomy-Resolve8630', 'smolsaturn', 'cocktails_and_corgis', 'Least-Ad-1287', 'moolett', 'duderanch_nurse', 'nephilimgoth666', 'Sarah-Sunshine9', 'poetaytoh', 'Throwawai36382', 'Sunshine_Savvy', 'chubbagrubb', 'Lkwtthecatdraggdn', 'No-Neighborhood3753', 'knbubba', 'kumparki', 'MelancholyBeautyXO', 'iliketoeatfoodnomnom', 'littlelou222', 'CommeChloe', 'Smallgrapes17', 'Potential-Swimmer945', 'Amy_cornish', 't-senpie', 'kaleileigh', 'i_love_horror_13', 'do1looklikeIcare', 'chloe_yo', 'ravenousbloodunicorn', 'anonymoustop', 'eeskymoo', 'lucysck', 'lepleinsoleil', 'Joonscene', 'LordRuby', 'eugclif', 'jasminelarios05', 'aryamagetro', 'sgreeb', 'Jeslon19', 'CurlyGirl_95', 'Mango-Mind', 'lhy13', 'ActiveShitter', 'eternalrevolver', 'comet4taily', 'harmlessCrow', 'HarryAndLana', 'Dyslexic_Dolphin03', 'zestygeese', 'legendariiiii', 'Ldennis98', 'Captsbunni28', 'Ahunteman', 'moon-cows', 'TipExpert7052', 'HereForALaugh714', 'alyssah01', 'BreeMint', '7730bubble', 'CoffeeChangesThings', 'pandas2017', 'lonelyhumanoid', 'RabbitDownInaHole', 'chatarungacheese', 'schmogini', 'NikkiD369', 'OddlyExotic', 'kanzetasman', 'Longjumping_Lock_474', 'cstlife1278', 'Future-Head-6516', '_poisonflower', 'lounge_l1zard', 'Pleasant-Movie-4287', 'AuntieJess4you', 'nicedreambarz', 'Lost_Swim9484', 'notsoeasypi', 'ssjr13', 'hellokoalaa', 'ex-tumblr-girl12116', '4handbob', '11_throwaways_later_', 'sarewr', 'lucillesmom', 'alinniebees', 'TimothyGonzalez', 'Random_Thoughts12', 'DarkStarComics333', 'Radiant_Albatross406', 'cfdtdrdd22220', 'onehalflaughing', 'Altrary', 'TerribleClassroom5', 'OzarkRedditor', 'Immediate-Let-7380', 'ActualRoom', 'orchid-walkeriana', 'xyz-reddit', 'palika6824', 'Historical_Count8375', 'ayealex228', 'invincible--', 'overlordmeow', 'Mad_Radge', 'AlternianTime', 'Lulu_zizi', 'JediAsh101', 'neonsol', 'lrhoades1', 'drphil07734', 'UnusualOctopus', 'big_mama_blitz', 'MehofMehtheMeh', 'uhohsminky', 'Goshdudette', 'neverpostsonreddit', 'Due_Start_8891', 'kvothes-lute', 'dreeisnotcool', 'yeonx3', 'Suspicious-Medicine3', 'hillbillyswag', 'CalligrapherSilly657', 'iseeseashells', 'Mizzanthrope99', 'Miserable_Elephant12', 'lovelylucille', 'TheMomDotCom89', 'Nihilistic-Fishstick', 'theyellowpants', 'North_Potato_7436', 'SetandPowder', 'zizalizabro', 'LaysWithTrash', 'luckyclaudy', 'msfelineenthusiast', 'TheWednesdayProject', 'TokiDokiHaato', 'w4ym3', 'greenh0use_ghost', 'RobotDeluxe', 'WaltzSecure2505', 'chocolat84', 'Prior_Expression8268', 'Mother_Orchid_1109', 'HundrumEngr', 'PhoxyGilbs', 'Allhailkendall', 'Sea-Cup-Tea', 'yoga_taco_sleep', 'PerfectPrincess97', 'gaypinapple_4', 'BachShitCrazy', 'XxEweEyexX', 'carrol_carters', 'Able_Half8000', 'schlaf888', 'ReblQueen', 'StareintotheSun2020', 'Schizowreckage', 'Ever_Love332', 'veronika_kajosova', 'tomsawyer333', 'Reasonable-Courage39', 'Comfortable_Water267', 'Cantthinkifany', 'Kdash21', 'skeletoesis', 'rabbitluckj', 'petrichorprincess45', 'ScorpioBunny97', 'very-oblivious', 'grill-tastic', 'dogmomofone', 'autumnatix', '__Daphne', 'biscuit_heathen', 'adventurelillypad', 'AlejaTuMirada', 'little_baby_pwincess', 'AdvancedMall169', 'WhyStateTheObvious', 'pockets_for_snacks', 'birdgoil', 'AdmirableGift1296', 'kathrynannemarie', 'lovelyfingertips', 'Available_Garbage764', 'constipatedcatlady', 'tequil-a', 'LPhamster', 'hollyboombah', 'Weekly-Marzipan-5455', 'OGgunter', 'owoitslance', 'Kerrbbott', 'Offbrandjillscott', 'AmandaFudge', 'libbyrae1987', 'allfalafel', 'madbunnys', 'Usobookie', 'starli29', '48niner', 'REM_loving_gal', 'mysisteradumbass', 'WikiTextBot', 'ballisticwhales', 'RainbowsandFireworks', 'Chaotic_Baptism', 'stu-pickles-3', 'Violets_and_honey', 'blvckcherry', 'NoSurrendo', 'Finemind', 'pericat_', 'ArianaRlva', 'knittedfuture', 'ImElison', 'Flutter_bat_16_', 'KProbs713', 'Alimoon29', 'Kay_Wizzle_34', 'mckinleyhennessey', 'cutetoes-420', 'thelittle', 'BubblyBreaker', 'PaigeMariia', 'RigidMember00', 'ADHDefeated', 'drakiferjen', 'Full_Speaker_912', 'zeezeemangostreet', 'sweetispoot', 'bmrisfh', 'Sm1thers03', 'Naru_Eternal', 'skincare_obssessed', 'ChaosQueen713', 'Significant_Cattle83', 'feminotorious', 'Top-Tap3217', 'feistysalsa', 'Alone_Rise_7056', 'helloblubb', 'thelavendermoon94', 'catashtrophe84', 'Swimming-Cake-4735', 'Visible-Ad221', 'advancedtaran', 'BlkBeauty_666', 'Valeshous', 'funny_bunny2', 'Leaf7818', 'jesiceez', 'alomaloma', 'CareElsy', 'DallyMads95', 'ElfHaze', '-StellarDoor', 'goldenbellaboo', 'Airbornequalified', 'ILoveTchaiTea', 'gdgardenlanterns', 'palls247', 'butterfly_eyes', 'Ray_Ray_96', 'RollingArtist', 'Dangerous_Cobbler_65', 'snappyirides', 'glassowater_', 'Children_consumer', 'imsnurgalicious', '33LivesAloneHas3cats', 'jelouise23', 'lazywriterno302', 'coffeebweath', 'slammy99', 'juiceboxfriend95', 'AlvinKai', 'LB56123', 'mightytastysoup', 'freckledcello', 'MonsterHighMandy', '_ImSalty', 'KimchiTheGreatest', 'prciouskivaa', 'lopsided-pancake', 'sibeliustheonion', 'mina-anaya', 'Snowysaku', 'updabumnobebes', 'Deelightfuldee', 'sierraalpha149', 'yeayea1211', 'babechel', 'ambriel86', 'MediumNewspaper69', 'plushed11', 'Otherwise-Painter-67', 'indigoneutrino', 'Holymolyneptune', 'Triene86', 'Glittering-Air2969', 'casuallybitchy', 'iaaiublaihapbafaiag', 'gia_ha', 'kindaahericane', 'greensandgables', 'RayneXAsh', 'queenofzoology', 'Gryffindor123', 'allyouneedarecats', 'Terrible_Jicama9398', 'RatherRetro', 'wanderwoman65', 'happyllamaparade', 'darkotics', 'Competitive-Run-9821', 'viennawaits88', 'ijustwanttobehonest', 'KarmicScorpion', 'lexplainer', 'Designer-Pattern3195', 't_cashmoney', 'gaynomadgirl', 'NeverEnoughMakeup', 'lluuni', 'hautemolls', 'industrial_hamster', 'Boring123af', 'youcanhavemycatbb', 'bigoldsunglasses', 'Jaclyn_22', 'happy_humanoid', 'Nocolon199230', 'taintedmelodies', 'VanimZen', 'bblrat', '3hit_0livia', 'madisonpotterr', 'Happy-Top9669', 'billiemint', 'DeliberateLiterate', 'throwaway56898542456', 'babymalibu', 'neko_sam_0234', 'Mrs_Attenborough', 'Critical_Opinion_119', 'Slytherinrunner', 'IKEA564', 'Round-Specialist7729', 'Think_Blacksmith_265', 'supposedly_educated', '--Aldebaran--', 'alohshine', 'ShaelTheFangirl', 'dreadpir8rob', 'Local-Lie-6152', 'fast_layne', 'reyuser', 'thro-w-away123', 'Rennat91', 'Ashamed_Comfort7567', 'littlerabbits72', 'guddadabhoota', 'Successful-Captain44', 'Adventurous_Panic917', 'cricketrmgss', 'mybellyhurtssobadow', 'Lychee-Prior', 'sardonicinterlude', 'STFUisright', 'badbullly', 'officialhunt', 'WillingGrape6', 'celia_swiftie', 'FragrantLynx', 'TurquoiseBoho', 'geniealisa', 'icuntcur', 'Larliya', 'xx__Jade__xx', 'NotCynicalAtAll', 'SeekingHealth23', 'ClumsyShadow', 'taumimarie', 'toofacedsugar17', 'dinodespot866', 'degrade_me_plis', 'tiggykins', 'Libelia', 'Loren_Drinks_Coffee', 'ml23346', 'SimonSpooner', 'jaegerhardt', 'Lacateras', 'influxofcoochie', 'euphoricplant9633', 'Babyroxasman', 'SuperMomn', 'Same-Affect-7939', 'sellboundcafe', 'mcksra', 'kawiah', 'salwj01', 'LaLunaRosa2020', 'gredzebra', 'Carry_Melodic', 'cestlavie908', 'hellhellhellhell', 'notsomuchhoney', 'Legitimate-Horror-78', 'xojinni', 'KnightOfTheLand', 'Inukshuk84', 'snortgiggles', 'StarSiiign', 'Pristine_Homework_38', 'jajnajzn', 'curiousjo1975', 'T--Frex', 'WeirdnessUnfolds', 'nopestillgotit', 'PromptZestyclose2182', 'Epiphanic_Eros', 'seneca333', 'No_Feeling_6037', 'Playful-Ride-6111', 'mauveaura', 'Salty_Temperature675', 'alyssa_boii', 'dizzyblinker', 'oceanmaango', 'SleepyKityKat', 'beetlejuicemayor', 'IdentityCrisis247', 'New_Specific_5802', 'flyingsquirrel33', 'bag-of-spanners', 'Let_Them_Eat_Cake24', 'miclisor', 'princessssconsuela', 'angiefkno', 'Wanderer_Brook', 'Assistant-Thin', 'Cfit9090', 'NOS326', 'UnderstandingDry2733', 'ChickEnergy', 'justanotherquaffle', 'marymilkovich', 'BittyLissy', 'lavender-pears', 'themacmonster', 'Thisisnotbekkah', 'DJLadyGooch', 'littellebaby', 'saturnthesixth', 'SignificantGanache', 'lizzielou22', 'BoredasUsual88', 'karmaleeta', 'Dmdel24', 'everygirl101', 'RennyxQ', 'Constipatedbride', '_ungrateful_', 'analslapchop', 'KarlMarxButVegan', 'virgofairy1970', 'meapsy', 'talihoeeee', 'ashes_9_', 'MegalodonDoDoDo', 'grandmabrown', 'Cardabella', 'PalatialPerspective', 'schalibali', 'Unique_Mood4412', 'Hancake097', 'ThrowRAfrhx', 'YuiKimura-', 'LargePomegranate2179', 'Intuition_love', 'TheMusicLounge', 'idkalissa', 'eeevol-', 'PowerfulTechnology9', 'EnderAvi', 'ThrowMeAwaySayIt', 'One-Report-4887', 'kungfookate', 'Journey333444', 'sunnysunnysunsun', 'roquea04', 'Particular_Use4902', '4723985throwaway', 'yllek_anon', 'Dont-Mind-Me-Ok', 'TinyTigerTamer', 'You_Go_Glen_Coco_', 'Kayyjayyemm', 'PrettyLonely123', 'Idontknowflycasual', 'NorthernWoman007', 'Bookwyrmgirl91', 'laureng026', 'catalyst553', 'livinglife_2626', 'Livieeee', 'AmythestFuckboi', 'baby_teeth_earrings', 'jebus_flippin_cripes', 'HawaiianPineapple31', 'Bubblezz11', 'CaraBee2022', 'Puzzled-Class7132', 'TheAvocadoSlayer', 'bitsandbobbins', 'Catpalum', 'idontkinkshame0', 'iwantd3d', 'LawyerBea', 'FetusPhoenix', 'rl_cookie', 'picklebreath_forlife', 'Lolorado5280', 'LokianEule', 'gracklito', 'NoseyParker_', 'Neither-Nebula-1527', 'SouthernFrosting6309', 'throwawaypeila', 'TriniLLC', 'mdoodss', 'causticalchemy', 'redhotpineapple', 'Keeks15', 'rosemarie321', 'lawschoolkat', 'mamaatb', 'TenshiAkuma1', 'Altruistic-Second325', 'jordyn_avery', 'creepygyal69', 'brekkabek', 'Ok-Kaleidoscope4381', 'Over_Illustrator_198', 'AvalancheQueen', 'mafa7', 'Poppet22', 'RunForLife88', 'rosegrowsbuds', 'saharathedesert', 'lady_in_the_streets', 'fruhlingsblumen1', 'PsychoFaerie', 'Uhhlaneuh', 'JPKtoxicwaste', 'Jenssauce', 'saphirekey', 'Tough-n-Stuff-12221', 'AgentCHAOS1967', 'chemuhk', 'whateverrr325', 'Mother_Trucker97', 'Me_Shay_Yay', 'No_Run5917', 'tomatoesgoboom', 'United_Durian_6826', 'adenosine3phosph8', 'Love2bakeCake', 'somnathverma978', 'MotherMfker', 'springjava263', 'taylorjo53', 'dontcallmechelly', 'BitchyNihilist420', 'only-depravity-here', 'Fair_Foundation_2239', 'blitzer_spritzer', 'FarDig2081', 'coccoL', 'ghobain', 'jo_lars', 'GulfCoastFlamingo', 'kvdenkohai', 'OldBatOfTheGalaxy', 'DepressedGhoast', 'yesibel', 'TinyResearch', 'liedaboutcake', 'Stonedstar', 'DelaraPorter', 'impostersoph', 'OrganicCouch84', 'SeriousVoice7305', 'jejefjdn', 'Embarrassed_Code_351', 'velikimokrimocerad', 'pediprincess100', 'WhatCanIEvenDoGuys', 'CrushedIcePepsi', 'Madeitforthethread', 'beachousebaby', 'Alliecp89', 'escapedfromthezoo', 'Disastrous-Share-391', 'sleepyyallyy', 'That_DamnYankee330', 'sillydustbunny', 'Coconutcream000', 'andiikats', 'rl3470', 'aVeryTinySmallSnake', 'chunkyRiceLady', 'ang_car', 'shythingpartysludge', 'hey_cali', 'Earlyecho', 'kittymuncher13463', 'rhiannon70s', 'letmesleepplz', 'heywhatsup82347', 'PMPunsandSeaShanties', 'nsdebbi', 'ohjackie91', 'baileash', 'wellnowheythere', 'Ratsmiths', 'flappingpussylips', 'me1s', 'ashl_litning', 'MoonlitMermaid-', 'spydermonkeej', 'PrincessofSongs', 'GOTisnotover77', 'warm_Caterpiller', 'pattyaq', 'AyenKurenai', 'King_Wohali', 'Putrid_Bathroom8572', 'addictedtoshindig', 'z0mb1equeen', 'throwaway_anoni', 'AdJaded4698', 'Mountain_Mood8062', 'Electronic-Income-39', 'HumanSushiBurrito', 'will_take_bribes', 'Slicksuzie', 'juxtaglometular', 'Pretend_Horror_2443', 'jaxpet101', 'mellyguens', 'mmrocker13', 'illiteratemad', 'theforcedreader', 'Enfp-airfairy', 'mcnuggg8', 'demogorgon_11', 'lightpinknails', 'heyimrichardzk', 'LmbLma', 'emoney1018', 'jad_wrldw', 'No-Cantaloupe1244', 'Sea-Avocado-2231', 'KingSwann', 'Civil-Explanation588', 'Kelterskelterr', 'kungpaola', 'burnttoenails69', '_cupcakewarrior_', 'ProofIntelligent8257', 'llemonjuiice', 'kayla-beep', 'CitrusMistress08', 'awwsnapcracklepop', 'VoodooDoII', 'BasicBitch_666', 'DangerousRiver9', 'nadysef', 'WaifuCoco', 'Jesster4200', 'Snowflake0804', 'bryhaight21', 'purplerosesgalore', 'vagabondsideshow', 'purpleteaaa', 'SweetPeaPotato', 'PSUAmandaC2010', 'bananamidriff', 'fluiDood', 'LostStatistician2038', 'pixie16502', 'act_normal', 'clamchowderlove', 'jbee8', 'Quietbirb', 'RamonaKwimby', 'saszew', 'ardynizuniasb-tch', 'crystal_clearit808', 'Shona7636', 'RoadPotential5047', 'CoroBora', 'Sshhhquiet', 'PaisleyBeth', 'Kinda_Fruity_', 'kylienotjenner29', 'Bre1500', 'AlertColdGhost4444', 'Asunai', 'Aggressive_Plenty426', 'Lizakaya', 'autoimmunequeen', 'Significant_Entry309', 'pinkwatermelooone', 'freegirl13', 'Environmental_Pea98', 'PWren16', 'AshSays_LGBT', 'SofiaFrancesca', 'Equivalent_You_7464', 'Numerous-Leg-8149', 'ladybawlz29', 'A_Fan888', 'YogurtBeneficial4554', 'HerbalistEra', 'ApathyIsntaTragedy', 'vintagetoyfinder', 'streetbirds', 'iLikeGooodboys', 'Kat9870', 'darkmattermattersmat', 'mydogsarecooler', 'maryshambles', 'UnlikelySteak2847', 'akOOch', 'Repulsive_Station389', 'Ok_Entrance_5404', 'Nearby-Elephant-9889', 'BlueberryAny965', 'hoohathrowaway0', 'Emmiey', 'mrabbit1961', 'hey-meow', 'gorlegg', 'willa61999', 'them______', 'itssalTEA', 'Sophrates_Regina', 'Pink_Floyd29', 'Ok_Package_593', 'Cultural_Ideal_4993', 'chaos-and-sauce', 'MeowingtotheOldies', 'LissClaire', 'No-Virus5447', 'goldenrose012', 'BluRain508', 'Nessamouse', 'biga55rat', 'idkwhatmyaestheticis', 'ajscpa', 'PepperSprayCat', 'thewhitepeach', 'GingerAphrodite', 'nikky31', 'TheKillingM0on', 'JamesFranco4Ever', 'graylie', 'royalflush59', 'Used_Initiative5651', 'disillusionedbean', 'twat_full_of_beans', 'Footzilla69', 'Juelzz_Santana', 'CJL3000', 'getxfitxgirl', 'searching_for_peace', 'alli-iss-a', 'africanalesbiana10', 'louie0413', 'darkprincessmidnight', 'RedCaveTree', 'abracadavars', 'werkin97', 'Elims123', 'fallingsatellites', 'AnotherAccountByChey', 'Amberslucky11', 'Tumbleweed_Evening', 'AllesK', 'boobycheekslinger', 'basicallybarbie', 'napnapnap', 'anonymousopottamus', 'fakeplasticcrow', 'Educational_Papaya59', 'Kxdeinee', 'bam_peasley', 'Lumpy_Lawfulness_', 'marvtv', 'WanderlustSimmer', 'ThatGirIay', 'doyouthinkimawhore', 'ecarmella4', 'allndrrose', 'man-repeller', 'GrendelLocke', 'converter-bot', 'TrickyTrackets', 'HelloPeopleImDed', 'FairInstruction8783', 'One_Bluejay6823', 'meamo6969', 'ocdreallysucks14', 'spiraldreamer', 'evaiam', 'mte87', 'anchronism', 'maybe_bb_', '17_pairs_of_earrings', 'biglybiglytremendous', 'tatemrie', 'triplehhh101993', 'Acceptable_Baker2974', 'samroesch', 'Weird-Work-6654', 'sirenwingsX', 'quebecca7', 'Apprehensive-Tree172', 'pigglepops', 'DuchessBatPenguin', 'missmetal', 'GirlonMangoStreet', 'that0n3girlj3nn', 'Moximal', 'elcatonero', 'jediofwatercolour', 'Puzzled_Ad8384', 'goldfishbraingirl', 'Useful_Parfait_8524', 'sunshinesparkle95', 'aakirkland', 'No_Kaleidoscope3226', 'EbonyRazrQueen', 'justagay509', 'Generic_Reddit_Bot', 'PerfectParfait5', 'dogsnob123', 'Lithiumqueen582', 'IDoDoodles', 'Rebecca24D', 'lixurboogers', 'GCQuest', 'stephhii', 'bbybats', 'ThrowawayUltaJFC', 'LunchRevolutionary89', 'ru4bl', 'PinkOveralls', 'alessandrawithss', 'car_of_men', 'TEA-in-the-G', 'IWantToTryEverythin', 'globeseeker8', 'quaizer79', 'Suitable_Wrongdoer85', 'fruitytetris', 'bloodmoonakali', 'lovethatjourney4me', 'coppyfloppy', 'oofieoofty', 'JennyLunetti', 'Landelyon', 'Most_Button_5881', 'earthspirit1147', 'canadianhon3y', '-queen_of_reddit-', 'comefindmetonowhere', 'tannith333', 'Bunny_P69', 'Netflix_Guzzler', 'notthatinnocent24', 'SheDoesntLikeYou', 'girafa_espacial', 'idely20', 'cammoose', 'Essiexo', 'EconomicsTiny447', 'More_Vegetable7061', 'sunshinerose12', 'LoopyRaspberry', 'tktg91', 'Kanibalxoxo', 'beingblonde900', 'rfoss2000', 'No-Beautiful6811', 'rainydaywrite', 'thethri11isgone', 'Luke_hs', 'slatheryslab', 'testicletoes', 'Aivleare123', 'Milkpiss215', 'Redstarshard', 'old_before_my_time', 'nekomeiko', 'pour_the_tea', 'Barrythehippo', 'Cassafrasslass', 'RainInTheWoods', 'Uwumaki7', 'autumnbottom2019', 'sroka_z_wysoka', 'NEDsaidIt', 'Lil-Miss-Anthropy', 'kaykayyolo17', 'ellenty', 'informationfreak123', 'kathryn_intimae', 'Ok_Insurance_7215', 'Incogcneat-o', 'snowbomb', 'Slackedelika', 'katf1sh', 'and_peggy_', 'I-OPsych18', 'Veryanxiousoften', 'imogensexistence', 'applepiehobbit', 'Lower_Ad_170', 'SnowyFlakes211', 'elola', 'Silverleaf001', 'Raven12177', 'MapHot8016', 'seekingpeace628', 'memetrain4life', 'LesPoissons90', 'Muffinman1111112', 'chakathemutt', 'BeanieMul1983', 'bumble843', 'gentleowl97', 'Typical_Honeydew_299', 'licegirl', 'chilloutyk', 'probablyinsweatpants', 'ConsistentJuice6757', 'sisuheart', 'Holiday-Till-2567', 'bigmouthxbelle', 'District_line', 'MsBluey', 'Winter-Sock9262', 'aWildPig', 'Minorihaaku', 'ske1etoncrush', 'fiobbo', 'Everybodygetroasted', 'DooglyOoklin', 'peachyindigochic', 'supernova10101', 'chocolateco0kie', 'igotseepeepeestd', 'Alternative_Cause297', '_lucy_blue', 'CatintheWall-eh', 'icecubekittylover', 'HeavySigh14', 'YourEponine', 'katelynwalk', 'moonjongup', '_bunnyholly', 'Arctic_azi', 'Mindless_Software732', '_oatmilk_', 'happygoluckylala', 'laurkiff', 'Jupitereyed', 'Ap-senLa', 'pemcake', 'cakekyo', 'MeMissBunny', 'EmphasisMelodic276', 'CoffeeANwaffles', 'jadedjade94', 'blueskies823', 'sexybeans', 'hahawhatjpg', 'isitmeorathrowaway', 'techtowers10oo', 'lavablobbob', 'Dirtypitprincess', 'picklefritzz', 'veggril', 'xoasp', 'sarter--767', 'IlluminatedLex17', 'ameliageika', 'Informal_Use_9229', 'goldielocket', 'raysayahm', 'amgirl1', 'GrumpySh33p', 'phimoo47', 'my_psychic_powers', 'NoSimoleons', 'sprinklebaloiga', 'cannachickgal', 'New-Affect2549', 'ThetaDot3', 'UnholyBitchYunalesca', 'red_razorlight221', 'bigmusclemcgee', 'Ep15437', 'LucrativeLlama', 'ProfessionalAd9721', 'recoveringdropout', 'wassermel0n', 'sml09', 'mistears0509', 'satan_6661', 'thespareone92', 'MoonlightStar6262', 'InquiringMind886', 'mil987', 'UsualMorning98', 'FLAANDRON', 'smoggyvirologist', 'Leiareii', 'I_eat_pasta_4_plane', 'throwaway99550092', 'agree-with-you', 'Sophiecourt', 'Hotskilletburn', 'TheyAreHidden', 'icanhasnoodlez', 'LovemeEatme', 'aspaciaa', 'DesignerUndereyeBags', 'Fickle_Freckle', 'PeachsPeaches', 'kinkthewink', 'Creative20something', 'mxdnite', 'maybeuknowmeornah', 'AnimeandRamenFan', 'cass2769', '111someone111', 'phiametal', 'Correct_Teach_6885', 'livinmystory', 'thankyou_places', 'throwawayacc2901', 'pulloutking42069', 'North_Flight4198', 'fivepoundsquash', 'burnt-urbex', 'Agreeable-Jacket9245', 'KahlanKhaos', 'Awesomesaws

In [30]:
users_df = pd.DataFrame(list(unique_users), columns=['user_id'])
posts_df_cleaned = posts_df[['post_id', 'subreddit', 'created_utc', 'selftext', 'post_url', 'post_title', 'link_flair_text', 'score', 'num_comments', 'upvote_ratio', 'post_author']]
comments_df_cleaned = comments_df[['post_id', 'comment', 'author']]

In [31]:
# Extract relationships
post_comment_relationships = comments_df[['post_id', 'comment']]
user_post_relationships = posts_df[['post_author', 'post_id']]
user_comment_relationships = comments_df[['author', 'comment']]

In [32]:
(users_df.head(), posts_df_cleaned.head(), comments_df_cleaned.head(), post_comment_relationships.head(), user_post_relationships.head(), user_comment_relationships.head())

(           user_id
 0
 1    resonatebliss
 2      Imchildfree
 3  Ill_Ocelot_9155
 4   cynical_genius,
   post_id     subreddit   created_utc  \
 0  kf0d1g  WomensHealth  1.608222e+09
 1  dwup3z  Healthyhooha  1.573842e+09
 2  hamqgj       Periods  1.592380e+09
 3  j8mxtl       Periods  1.602346e+09
 4  mqc0v5       Periods  1.618349e+09

                                             selftext  \
 0  Hey! I spoke with them on the phone, and they ...
 1
 2
 3
 4

                                             post_url  \
 0  https://www.reddit.com/r/WomensHealth/comments...
 1                https://i.redd.it/ua4z8e477wy31.jpg
 2                https://i.redd.it/h83zzjacdf551.jpg
 3                https://i.redd.it/2fo1u3ioias51.jpg
 4                https://i.redd.it/83x11rfxd0t61.jpg

                                           post_title link_flair_text  score  \
 0  Please sign petition to get nerves in the clit...                   2466
 1  I know this is apart of the standardized proce...                   2407
 2                I'm sure every person here relates.           Fluff   2357
 3                                                  🩸           Fluff   2176
 4                               why is this so true?           Fluff   2113

    num_comments  upvote_ratio   post_author
 0           183          1.00   jessica_pin
 1            49          0.99
 2            16          1.00  noorhaider97
 3            16          1.00
 4            72          1.00    KitKat1287  ,
   post_id                                            comment         author
 0  kf0d1g  Oh no. Oh no NO. I’m so sorry. Signed sealed d...  ohhh_RaMoannn
 1  kf0d1g     Why are vaginas still taboo??? I don’t get it.       Dracalia
 2  kf0d1g  *Has this been cross posted to r/twoxchromosom...         bex505
 3  kf0d1g  How does their excuse that it "doesn't fit the...    shanaenae91
 4  kf0d1g   Signed and donated 5000 shares. You are a saint!    BooBooCanoe,
   post_id                                            comment
 0  kf0d1g  Oh no. Oh no NO. I’m so sorry. Signed sealed d...
 1  kf0d1g     Why are vaginas still taboo??? I don’t get it.
 2  kf0d1g  *Has this been cross posted to r/twoxchromosom...
 3  kf0d1g  How does their excuse that it "doesn't fit the...
 4  kf0d1g   Signed and donated 5000 shares. You are a saint!,
     post_author post_id
 0   jessica_pin  kf0d1g
 1                dwup3z
 2  noorhaider97  hamqgj
 3                j8mxtl
 4    KitKat1287  mqc0v5,
           author                                            comment
 0  ohhh_RaMoannn  Oh no. Oh no NO. I’m so sorry. Signed sealed d...
 1       Dracalia     Why are vaginas still taboo??? I don’t get it.
 2         bex505  *Has this been cross posted to r/twoxchromosom...
 3    shanaenae91  How does their excuse that it "doesn't fit the...
 4    BooBooCanoe   Signed and donated 5000 shares. You are a saint!)